language: node_js

sudo: true

node_js:
  - '10'
  - '12'
  - v12
  - v10

before_install:
  - sudo apt-get update && sudo apt-get install expect
  - sudo pip install -U docker-compose
  - docker --version && docker-compose --version

install:
  - npm install

script:
  - npm run lint
  - npm run test

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - node_modules

services:
  - docker

branches:
  only:
    - master
